
#ifndef _PLATFORM_H    
#define _PLATFORM_H

#define _SUPPRESS_PLIB_WARNING
#define _DISABLE_OPENADC10_CONFIGPORT_WARNING

#define SYSCLK 40000000
#define LED_GREEN LATBbits.LATB14
#define LED_RED LATBbits.LATB9




#endif
